export ZDOTDIR=$HOME

# for pyenv
if [ -d $HOME/.pyenv ];
then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
fi

# for poetry
export PATH="$HOME/.local/bin:$PATH"

